server:
  port: 10051

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coderinfo_db?useUnicode=true&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    tomcat:
      connection-timeout: 30000
      max-lifetime: 1800000
      max-pool-size: 15
      min-idle: 5
      connection-test-query: select 1